package usecase

import "github.com/evandrarf/dinacom-be/internal/delivery/http/entity"

var QuestionBank = []entity.QuestionTemplate{
	// ==================== EASY QUESTIONS (15 templates) ====================
	// b-d confusion (most common)
	{
		ID:               "e-bd-1",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "b-d",
		TargetLetter:     "B",
		CorrectWord:      "BATU",
		Distractors:      []string{"DATU", "MATU", "SATU"},
	},
	{
		ID:               "e-bd-2",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "b-d",
		TargetLetter:     "D",
		CorrectWord:      "DASI",
		Distractors:      []string{"BASI", "PASI", "NASI"},
	},
	{
		ID:               "e-bd-3",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "b-d",
		TargetLetter:     "B",
		CorrectWord:      "BOLA",
		Distractors:      []string{"DOLA", "KOLA", "SOLA"},
	},
	{
		ID:               "e-bd-4",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "b-d",
		TargetLetter:     "D",
		CorrectWord:      "DADU",
		Distractors:      []string{"BADU", "RADU", "KADU"},
	},
	{
		ID:               "e-bd-5",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "b-d",
		TargetLetter:     "B",
		CorrectWord:      "BUKU",
		Distractors:      []string{"DUKU", "SUKU", "TUKU"},
	},
	{
		ID:               "e-bd-6",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "b-d",
		TargetLetter:     "B",
		CorrectWord:      "BABI",
		Distractors:      []string{"DABI", "KABI", "RABI"},
	},
	{
		ID:               "e-bd-7",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "b-d",
		TargetLetter:     "D",
		CorrectWord:      "DADA",
		Distractors:      []string{"BADA", "RADA", "KADA"},
	},

	// m-w confusion
	{
		ID:               "e-mw-1",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "m-w",
		TargetLetter:     "M",
		CorrectWord:      "MAMA",
		Distractors:      []string{"WAMA", "PAPA", "RAMA"},
	},
	{
		ID:               "e-mw-2",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "m-w",
		TargetLetter:     "W",
		CorrectWord:      "WAJA",
		Distractors:      []string{"MAJA", "RAJA", "TAJA"},
	},
	{
		ID:               "e-mw-3",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "m-w",
		TargetLetter:     "M",
		CorrectWord:      "MEJA",
		Distractors:      []string{"WEJA", "REJA", "TEJA"},
	},
	{
		ID:               "e-mw-4",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "m-w",
		TargetLetter:     "W",
		CorrectWord:      "WALI",
		Distractors:      []string{"MALI", "BALI", "KALI"},
	},

	// p-q confusion
	{
		ID:               "e-pq-1",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "p-q",
		TargetLetter:     "P",
		CorrectWord:      "PAKU",
		Distractors:      []string{"QAKU", "BAKU", "MAKU"},
	},
	{
		ID:               "e-pq-2",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "p-q",
		TargetLetter:     "P",
		CorrectWord:      "PAGI",
		Distractors:      []string{"QAGI", "BAGI", "LAGI"},
	},

	// n-u confusion (rotational)
	{
		ID:               "e-nu-1",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "n-u",
		TargetLetter:     "N",
		CorrectWord:      "NASI",
		Distractors:      []string{"UASI", "BASI", "RASI"},
	},
	{
		ID:               "e-nu-2",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "n-u",
		TargetLetter:     "N",
		CorrectWord:      "NAGA",
		Distractors:      []string{"UAGA", "RAGA", "TAGA"},
	},
	{
		ID:               "e-nu-3",
		Difficulty:       entity.DifficultyEasy,
		TargetLetterPair: "n-u",
		TargetLetter:     "U",
		CorrectWord:      "ULAR",
		Distractors:      []string{"NLAR", "ILAR", "JLAR"},
	},

	// ==================== MEDIUM QUESTIONS (14 templates) ====================
	// b-d patterns
	{
		ID:               "m-bd-1",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "b-d",
		TargetLetter:     "B",
		CorrectWord:      "BARU",
		Distractors:      []string{"DARU", "BIRU", "DURI"},
	},
	{
		ID:               "m-bd-2",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "b-d",
		TargetLetter:     "D",
		CorrectWord:      "DURI",
		Distractors:      []string{"BURI", "BIRU", "KURI"},
	},
	{
		ID:               "m-bd-3",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "b-d",
		TargetLetter:     "B",
		CorrectWord:      "BAYI",
		Distractors:      []string{"DAYI", "RABI", "KADI"},
	},
	{
		ID:               "m-bd-4",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "b-d",
		TargetLetter:     "D",
		CorrectWord:      "DARI",
		Distractors:      []string{"BARI", "HARI", "LARI"},
	},
	{
		ID:               "m-bd-5",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "b-d",
		TargetLetter:     "B",
		CorrectWord:      "BUDI",
		Distractors:      []string{"DUDI", "RUDI", "SUDI"},
	},
	{
		ID:               "m-bd-6",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "b-d",
		TargetLetter:     "D",
		CorrectWord:      "DUIT",
		Distractors:      []string{"BUIT", "SUIT", "TUIT"},
	},

	// m-w patterns
	{
		ID:               "m-mw-1",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "m-w",
		TargetLetter:     "M",
		CorrectWord:      "MATI",
		Distractors:      []string{"WATI", "PATI", "SATI"},
	},
	{
		ID:               "m-mw-2",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "m-w",
		TargetLetter:     "W",
		CorrectWord:      "WARNA",
		Distractors:      []string{"MARNA", "BARNA", "DARNA"},
	},
	{
		ID:               "m-mw-3",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "m-w",
		TargetLetter:     "M",
		CorrectWord:      "MADU",
		Distractors:      []string{"WADU", "RADU", "PADU"},
	},
	{
		ID:               "m-mw-4",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "m-w",
		TargetLetter:     "W",
		CorrectWord:      "WAKTU",
		Distractors:      []string{"MAKTU", "FAKTU", "PAKTU"},
	},

	// p-q patterns
	{
		ID:               "m-pq-1",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "p-q",
		TargetLetter:     "P",
		CorrectWord:      "PADI",
		Distractors:      []string{"QADI", "RADI", "BADI"},
	},
	{
		ID:               "m-pq-2",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "p-q",
		TargetLetter:     "P",
		CorrectWord:      "PETA",
		Distractors:      []string{"QETA", "META", "BETA"},
	},

	// n-u patterns
	{
		ID:               "m-nu-1",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "n-u",
		TargetLetter:     "N",
		CorrectWord:      "NAMA",
		Distractors:      []string{"UAMA", "RAMA", "TAMA"},
	},
	{
		ID:               "m-nu-2",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "n-u",
		TargetLetter:     "N",
		CorrectWord:      "NANTI",
		Distractors:      []string{"UANTI", "BANTI", "PANTI"},
	},
	{
		ID:               "m-nu-3",
		Difficulty:       entity.DifficultyMedium,
		TargetLetterPair: "n-u",
		TargetLetter:     "U",
		CorrectWord:      "UDARA",
		Distractors:      []string{"NDARA", "ADARA", "IDARA"},
	},

	// ==================== HARD QUESTIONS (18 templates) ====================
	// Complex b-d patterns
	{
		ID:               "h-bd-1",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "b-d",
		TargetLetter:     "B",
		CorrectWord:      "BERITA",
		Distractors:      []string{"DERITA", "CERITA", "SERITA"},
	},
	{
		ID:               "h-bd-2",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "b-d",
		TargetLetter:     "D",
		CorrectWord:      "DERITA",
		Distractors:      []string{"BERITA", "CERITA", "SERITA"},
	},
	{
		ID:               "h-bd-3",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "b-d",
		TargetLetter:     "B",
		CorrectWord:      "BAKTI",
		Distractors:      []string{"DAKTI", "SAKTI", "FAKTI"},
	},
	{
		ID:               "h-bd-4",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "b-d",
		TargetLetter:     "D",
		CorrectWord:      "DALAM",
		Distractors:      []string{"BALAM", "SALAM", "MALAM"},
	},
	{
		ID:               "h-bd-5",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "b-d",
		TargetLetter:     "B",
		CorrectWord:      "BUDAYA",
		Distractors:      []string{"DUDAYA", "SUDAYA", "RUDAYA"},
	},
	{
		ID:               "h-bd-6",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "b-d",
		TargetLetter:     "D",
		CorrectWord:      "DUNIA",
		Distractors:      []string{"BUNIA", "SUNIA", "RUNIA"},
	},

	// Complex m-w patterns
	{
		ID:               "h-mw-1",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "m-w",
		TargetLetter:     "M",
		CorrectWord:      "MAWAR",
		Distractors:      []string{"WAWAR", "SAWAR", "TAWAR"},
	},
	{
		ID:               "h-mw-2",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "m-w",
		TargetLetter:     "W",
		CorrectWord:      "WAJIB",
		Distractors:      []string{"MAJIB", "SAJIB", "TAJIB"},
	},
	{
		ID:               "h-mw-3",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "m-w",
		TargetLetter:     "M",
		CorrectWord:      "MIMPI",
		Distractors:      []string{"WIMPI", "SIMPI", "TIMPI"},
	},
	{
		ID:               "h-mw-4",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "m-w",
		TargetLetter:     "W",
		CorrectWord:      "WAJAH",
		Distractors:      []string{"MAJAH", "RAJAH", "SAJAH"},
	},

	// Complex p-q patterns
	{
		ID:               "h-pq-1",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "p-q",
		TargetLetter:     "P",
		CorrectWord:      "PAHAM",
		Distractors:      []string{"QAHAM", "SAHAM", "RAHAM"},
	},
	{
		ID:               "h-pq-2",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "p-q",
		TargetLetter:     "P",
		CorrectWord:      "PIDATO",
		Distractors:      []string{"QIDATO", "SIDATO", "RIDATO"},
	},

	// Complex n-u patterns
	{
		ID:               "h-nu-1",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "n-u",
		TargetLetter:     "N",
		CorrectWord:      "NEGARA",
		Distractors:      []string{"UEGARA", "SEGARA", "MEGARA"},
	},
	{
		ID:               "h-nu-2",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "n-u",
		TargetLetter:     "N",
		CorrectWord:      "NAFAS",
		Distractors:      []string{"UAFAS", "RAFAS", "KAFAS"},
	},
	{
		ID:               "h-nu-3",
		Difficulty:       entity.DifficultyHard,
		TargetLetterPair: "n-u",
		TargetLetter:     "U",
		CorrectWord:      "UCAPAN",
		Distractors:      []string{"NCAPAN", "ACAPAN", "ICAPAN"},
	},
}
